### PR TITLE
command piping

### PR DESCRIPTION
**Pull request by brandon-reinhart**
In progress work on an error handling property.

Goal: Direct output from a command to some arbitrary system.

```rust
fn handle_ok(In(value): In<u32>) {
    println!("Everything is fine. See: {}", value);
}

fn report_error(In(error): In<&'static str>) {
    println!("Error: {}", error);
}

#[command(ok = handle_ok, err = report_error)]
fn error_out(world: &mut World, success: bool) -> Result<u32, &'static str> {
    if success {
        Ok(42)
    } else {
        Err("Something went wrong")
    }
}

#[command(ok = handle_ok)]
fn only_ok(world: &mut World) -> Result<u32, &'static str> {
    Ok(3)
}

#[command(err = report_error)]
fn only_err(world: &mut World) -> Result<u32, &'static str> {
    Err("It's okay to be in error.")
}
```

General pipes are now supported:
```rust
fn do_a_thing(In(value): In<i32>) {
   // value will be the result of command_with_output
}

#[command(pipe = do_a_thing)]
fn command_with_output(world: &mut World) -> i32 {
    7
}
```

### CODE REVIEW

**Comment by brandon-reinhart** [comment]
We could probably use some tests. I can definitely see this crate starting to regress as features are added, given the way it would be possible to parse a bunch of stuff that works fine down several uses cases and blows up an untested one.

**Comment by brandon-reinhart** [comment]
Thanks for letting me work on this! I've never done any macro stuff in Rust before. Pretty cool.

**Comment by thebluefish** [comment]
> We could probably use some tests. I can definitely see this crate starting to regress as features are added, given the way it would be possible to parse a bunch of stuff that works fine down several uses cases and blows up an untested one.

I would definitely like to cover the new features. 

Since this PR allows defining return types, two tests are now failing. They can both be deleted, along with their corresponding `.stderr` files.
```
tests\ui\return_type.rs
tests\ui\return_type_entity.rs
```

**Comment by brandon-reinhart** [comment]
> > We could probably use some tests. I can definitely see this crate starting to regress as features are added, given the way it would be possible to parse a bunch of stuff that works fine down several uses cases and blows up an untested one.
> 
> I would definitely like to cover the new features.
> 
> Since this PR allows defining return types, two tests are now failing. They can both be deleted, along with their corresponding `.stderr` files.
> 
> ```
> tests\ui\return_type.rs
> tests\ui\return_type_entity.rs
> ```

I totally missed this. Will fix shortly.

**Comment by brandon-reinhart** [comment]
Tests are now available:

- A negative test for a handler missing an argument.
- Positive tests for ok / err handlers executing correctly.

**Comment by brandon-reinhart** [comment]
There's one other thing I'd like to do, but am not sure how to approach it.

I want to also be able to call the "original" fn, for example, to compose commands and calls in different ways...

```rust
let result = error_out_with_result(...);
// ... my code to handle result without using a command
```
But this is peeking under the hood. I happen to know the decorated "_with_result" version of the fn exists. What would be a better way to handle this?

**Comment by brandon-reinhart** [comment]
FWIW, I've updated my own project to use this branch and it works great!

**Comment by brandon-reinhart** [comment]
fixes #2

**Pull request closed without merging**
